import { StrictMode, useEffect, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { NavLink, Outlet, useLocation } from 'react-router-dom'
import { BrowserRouter, Routes, Route } from 'react-router-dom'
import {
  Activity, ArrowUpRight, BookOpen, Boxes, Cpu, FileText, Gauge, HardDrive,
  LayoutDashboard, MessageSquare, MoreHorizontal, Plus, Search, Settings,
  ShieldCheck, Sparkles, UploadCloud, WifiOff, X,
} from 'lucide-react'
import { api, type ConnectionState, type ConfigResponse, type DocumentRecord, type HardwareResponse, type RuntimeResponse, type Citation, type StudyResponse, type MultimodalCapabilities, type DashboardSnapshot } from './api'
import './styles.css'
import './document-styles.css'

const navGroups = [
  { label: 'Workspace', items: [
    { to: '/', label: 'Dashboard', icon: LayoutDashboard },
    { to: '/documents', label: 'Documents', icon: FileText },
    { to: '/knowledge', label: 'Knowledge', icon: Boxes },
    { to: '/chat', label: 'Chat', icon: MessageSquare },
    { to: '/study', label: 'Study', icon: BookOpen },
  ]},
  { label: 'System', items: [
    { to: '/hardware', label: 'Hardware', icon: Cpu },
    { to: '/benchmark', label: 'Benchmark', icon: Gauge },
    { to: '/settings', label: 'Settings', icon: Settings },
  ]},
]

function AppShell() {
  const [connected, setConnected] = useState<ConnectionState>('loading')
  const location = useLocation()
  const [mobileNav, setMobileNav] = useState(false)
  const title = location.pathname === '/' ? 'Dashboard' : navGroups.flatMap((group) => group.items).find((item) => item.to === location.pathname)?.label ?? 'SnapMind'

  useEffect(() => {
    api.health().then(() => setConnected('connected')).catch(() => setConnected('error'))
  }, [])

  return <div className="app-shell">
    <aside className={`sidebar ${mobileNav ? 'sidebar-open' : ''}`}>
      <div className="brand"><div className="brand-mark"><Sparkles size={18} /></div><span>Snap<span className="brand-accent">Mind</span></span></div>
      <div className="sidebar-label">Navigate</div>
      <nav className="nav-list">
        {navGroups.map((group) => <div className="nav-group" key={group.label}>
          <div className="nav-group-label">{group.label}</div>
          {group.items.map(({ to, label, icon: Icon }) => <NavLink end={to === '/'} to={to} key={to} onClick={() => setMobileNav(false)} className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}><Icon size={17} strokeWidth={1.8} /><span>{label}</span>{label === 'Chat' && <span className="nav-dot" />}</NavLink>)}
        </div>)}
      </nav>
      <div className="sidebar-footer"><div className="privacy-mark"><ShieldCheck size={17} /><div><strong>Local workspace</strong><span>Cloud features off</span></div></div><div className="user-chip"><div className="avatar">KS</div><div><strong>Personal space</strong><span>Private by default</span></div><MoreHorizontal size={16} /></div></div>
    </aside>
    {mobileNav && <button className="mobile-backdrop" onClick={() => setMobileNav(false)} aria-label="Close navigation" />}
    <div className="main-frame">
      <header className="topbar"><button className="mobile-menu" onClick={() => setMobileNav(true)} aria-label="Open navigation"><Boxes size={20} /></button><div><div className="breadcrumb">Workspace <span>/</span> <strong>{title}</strong></div></div><div className="topbar-actions"><div className={`connection-pill ${connected}`}><span className="status-dot" />{connected === 'connected' ? 'Backend connected' : connected === 'error' ? 'Backend offline' : 'Connecting'}</div><button className="icon-button" aria-label="Search"><Search size={18} /></button><div className="top-avatar">KS</div></div></header>
      <main className="page-container"><Outlet /></main>
    </div>
  </div>
}

function Dashboard() {
  const [dashboard, setDashboard] = useState<DashboardSnapshot | null>(null)
  const [error, setError] = useState(false)
  useEffect(() => { api.dashboard().then(setDashboard).catch(() => setError(true)) }, [])
  return <>
    <section className="welcome-row"><div><p className="eyebrow">{getGreeting()} <span className="eyebrow-line" /></p><h1>Your private knowledge<br /><em>workspace.</em></h1><p className="subtitle">A focused place to collect, understand, and revisit what matters.</p></div><NavLink to="/documents" className="primary-button"><Plus size={19} /> Import document</NavLink></section>
    {error && <div className="alert error"><WifiOff size={17} /> The local backend is unreachable. Live system status is unavailable.</div>}
    {!dashboard && !error ? <div className="dashboard-loading"><Activity className="spin" size={23} /> Loading workspace snapshot...</div> : dashboard && <><section className="stats-grid"><StatCard label="Documents" value={String(dashboard.document_count)} detail={dashboard.document_count ? 'Stored locally' : 'Nothing imported yet'} icon={FileText} /><StatCard label="Knowledge chunks" value={String(dashboard.indexed_chunk_count)} detail={dashboard.indexed_chunk_count ? 'Indexed locally' : 'Index not available'} icon={Boxes} /><StatCard label="Questions asked" value="--" detail="Session activity" icon={MessageSquare} /><StatCard label="Study items" value="--" detail="Generated on demand" icon={BookOpen} /></section><section className="dashboard-grid"><div className="panel status-panel"><div className="panel-heading"><div><p className="eyebrow">System overview</p><h2>Ready when you are</h2></div><Activity className="heading-icon" size={20} /></div><div className="status-list"><StatusRow icon={Sparkles} label="Local AI" value={dashboard.ai.status === 'ready' ? 'Ready' : 'Unavailable'} detail={dashboard.ai.model} tone={dashboard.ai.status === 'ready' ? 'good' : 'muted'} /><StatusRow icon={Cpu} label="Hardware" value={dashboard.hardware.cpu_status === 'available' ? 'Detected' : 'Unknown'} detail={dashboard.hardware.processor} tone="muted" /><StatusRow icon={ShieldCheck} label="Accelerator" value={dashboard.hardware.npu_status === 'unknown' ? 'Not verified' : dashboard.hardware.npu_status} detail={dashboard.hardware.npu_evidence} tone="muted" /></div></div><div className="panel next-panel"><div className="panel-heading"><div><p className="eyebrow">Get started</p><h2>Build your library</h2></div><ArrowUpRight className="heading-icon" size={20} /></div><div className="empty-illustration"><div className="upload-icon"><UploadCloud size={25} /></div><p>Import a document to begin</p><span>Supported local formats: PDF, TXT, Markdown, and DOCX.</span><NavLink to="/documents" className="secondary-button">Explore documents <ArrowUpRight size={15} /></NavLink></div></div></section><section className="section-block"><div className="section-heading"><div><p className="eyebrow">Your library</p><h2>Recent documents</h2></div><NavLink to="/documents" className="text-link">View all <ArrowUpRight size={15} /></NavLink></div>{dashboard.recent_documents.length ? <div className="recent-list">{dashboard.recent_documents.map((document) => <NavLink to="/documents" className="recent-item" key={document.document_id}><div className="recent-type">{document.file_type.toUpperCase()}</div><div><strong>{document.filename}</strong><span>{document.processing_status === 'indexed' ? 'Indexed locally' : document.processing_status}</span></div><ArrowUpRight size={15} /></NavLink>)}</div> : <div className="empty-library"><FileText size={23} /><div><strong>No recent documents</strong><span>Your imported sources will appear here.</span></div></div>}</section></>}
  </>
}

function StatCard({ label, value, detail, icon: Icon }: { label: string; value: string; detail: string; icon: typeof FileText }) { return <div className="stat-card"><div className="stat-top"><span>{label}</span><Icon size={17} /></div><strong>{value}</strong><small>{detail}</small></div> }
function StatusRow({ icon: Icon, label, value, detail, tone }: { icon: typeof Cpu; label: string; value: string; detail: string; tone: string }) { return <div className="status-row"><div className="status-icon"><Icon size={17} /></div><div className="status-copy"><strong>{label}</strong><span>{detail}</span></div><div className={`status-value ${tone}`}><span className="status-dot" />{value}</div></div> }
function getGreeting() { const hour = new Date().getHours(); return hour < 12 ? 'Good morning' : hour < 18 ? 'Good afternoon' : 'Good evening' }

function DocumentsPage() {
  const [documents, setDocuments] = useState<DocumentRecord[]>([])
  const [query, setQuery] = useState('')
  const [filter, setFilter] = useState('all')
  const [busy, setBusy] = useState(true)
  const [error, setError] = useState('')
  const [dragging, setDragging] = useState(false)
  const inputRef = useRef<HTMLInputElement>(null)
  const load = () => { setBusy(true); api.documents().then((response) => { setDocuments(response.documents); setError('') }).catch((reason: Error) => setError(reason.message)).finally(() => setBusy(false)) }
  useEffect(load, [])
  const upload = async (file: File) => { setBusy(true); try { const document = await api.uploadDocument(file); setDocuments((current) => [document, ...current]); setError('') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Upload failed.') } finally { setBusy(false) } }
  const shown = documents.filter((document) => (filter === 'all' || document.processing_status === filter) && document.filename.toLowerCase().includes(query.toLowerCase()))
  return <section className="documents-page"><div className="page-heading"><div className="page-intro"><p className="eyebrow">Workspace</p><h1>Documents</h1><p className="subtitle">Your local document library. Files are stored and processed on this device.</p></div><button className="primary-button" onClick={() => inputRef.current?.click()}><Plus size={19} /> Import document</button><input ref={inputRef} hidden type="file" accept=".pdf,.txt,.md,.markdown,.docx" onChange={(event) => event.target.files?.[0] && upload(event.target.files[0])} /></div>
    {error && <div className="alert error"><WifiOff size={17} /> {error}</div>}
    <div className={`drop-zone ${dragging ? 'dragging' : ''}`} onDragOver={(event) => { event.preventDefault(); setDragging(true) }} onDragLeave={() => setDragging(false)} onDrop={(event) => { event.preventDefault(); setDragging(false); const file = event.dataTransfer.files[0]; if (file) upload(file) }}><UploadCloud size={22} /><div><strong>Drop a document here</strong><span>or choose a file from your device · PDF, TXT, Markdown, DOCX · 50 MB max</span></div><button className="secondary-button" onClick={() => inputRef.current?.click()}>Choose file</button></div>
    <div className="library-toolbar"><div className="search-field"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search documents..." /></div><select value={filter} onChange={(event) => setFilter(event.target.value)} aria-label="Filter documents"><option value="all">All statuses</option><option value="indexed">Indexed</option><option value="processing">Processing</option><option value="failed">Failed</option></select></div>
    {busy && documents.length === 0 ? <div className="library-state"><Activity className="spin" size={23} /> Loading document library...</div> : shown.length === 0 ? <div className="library-state"><FileText size={25} /><strong>{documents.length ? 'No matching documents' : 'Your library is empty'}</strong><span>{documents.length ? 'Try a different search or status filter.' : 'Import a local source to start building your knowledge base.'}</span></div> : <div className="document-grid">{shown.map((document) => <DocumentCard key={document.document_id} document={document} onDelete={() => { api.deleteDocument(document.document_id).then(() => setDocuments((current) => current.filter((item) => item.document_id !== document.document_id))).catch((reason: Error) => setError(reason.message)) }} onRetry={() => api.retryDocument(document.document_id).then((updated) => setDocuments((current) => current.map((item) => item.document_id === updated.document_id ? updated : item))).catch((reason: Error) => setError(reason.message))} />)}</div>}
  </section>
}
function DocumentCard({ document, onDelete, onRetry }: { document: DocumentRecord; onDelete: () => void; onRetry: () => void }) { return <article className="document-card"><div className="document-card-top"><div className="file-type">{document.file_type.toUpperCase()}</div><button className="delete-button" onClick={onDelete} aria-label={`Delete ${document.filename}`}><X size={16} /></button></div><h3 title={document.filename}>{document.filename}</h3><div className="document-meta"><span>{formatBytes(document.file_size)}</span><span>{document.page_count ? `${document.page_count} pages` : document.text_length ? `${document.text_length.toLocaleString()} characters` : 'Metadata unavailable'}</span></div><div className={`processing-status ${document.processing_status}`}><span className="status-dot" />{document.processing_status === 'indexed' ? 'Indexed' : document.processing_status === 'processing' ? 'Processing' : 'Processing failed'}</div>{document.error_message && <p className="document-error">{document.error_message}</p>}{document.processing_status === 'failed' && <button className="retry-button" onClick={onRetry}>Retry processing</button>}</article> }
function formatBytes(bytes: number) { if (bytes < 1024) return `${bytes} B`; if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`; return `${(bytes / 1024 / 1024).toFixed(1)} MB` }

function KnowledgePage() {
  const [query, setQuery] = useState('')
  const [results, setResults] = useState<import('./api').KnowledgeChunk[]>([])
  const [indexedChunks, setIndexedChunks] = useState(0)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const search = async () => { if (!query.trim()) { setError('Enter a question or phrase to search your knowledge base.'); return }; setBusy(true); setError(''); try { const response = await api.searchKnowledge(query); setResults(response.results); setIndexedChunks(response.indexed_chunks) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Knowledge search failed.') } finally { setBusy(false) } }
  return <section className="knowledge-page"><div className="page-intro"><p className="eyebrow">Workspace</p><h1>Knowledge</h1><p className="subtitle">Search the indexed chunks that will ground future SnapMind answers.</p></div><div className="knowledge-summary"><div><span>Indexed chunks</span><strong>{indexedChunks || '--'}</strong></div><div><span>Search mode</span><strong>Local retrieval</strong></div><div><span>Source grounding</span><strong>Metadata preserved</strong></div></div><div className="knowledge-search"><div className="search-field"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && search()} placeholder="Search your knowledge..." /><button onClick={search} disabled={busy}>{busy ? 'Searching...' : 'Search'}</button></div></div>{error && <div className="alert error"><WifiOff size={17} /> {error}</div>}{!busy && !error && results.length === 0 ? <div className="library-state"><Boxes size={25} /><strong>{indexedChunks ? 'Search your indexed knowledge' : 'No indexed knowledge yet'}</strong><span>{indexedChunks ? 'Results will include the source document and preserved metadata.' : 'Import and process a document to create searchable chunks.'}</span></div> : <div className="knowledge-results">{results.map((result) => <article className="knowledge-result" key={result.chunk_id}><div className="result-top"><span className="file-type">{result.file_type.toUpperCase()}</span><span className="relevance">{Math.round(result.relevance * 100)}% relevant</span></div><h3>{result.filename}</h3><p>{result.text}</p><div className="result-meta"><span>Chunk {result.position + 1}</span>{result.page && <span>Page {result.page}</span>}{result.section && <span>{result.section}</span>}</div></article>)}</div>}</section>
}

function HardwarePage() {
  const [hardware, setHardware] = useState<HardwareResponse | null>(null)
  const [runtime, setRuntime] = useState<RuntimeResponse | null>(null)
  const [multimodal, setMultimodal] = useState<MultimodalCapabilities | null>(null)
  const [error, setError] = useState('')
  useEffect(() => { Promise.all([api.hardware(), api.runtime(), api.multimodalCapabilities()]).then(([hardwareResponse, runtimeResponse, multimodalResponse]) => { setHardware(hardwareResponse); setRuntime(runtimeResponse); setMultimodal(multimodalResponse) }).catch((reason: Error) => setError(reason.message)) }, [])
  const capabilities = hardware ? [hardware.device.cpu, hardware.device.gpu, hardware.device.npu] : []
  const multimodalItems = multimodal ? [multimodal.ocr, multimodal.image_understanding, multimodal.speech_to_text] : []
  return <section className="hardware-page"><div className="page-intro"><p className="eyebrow">System</p><h1>Hardware</h1><p className="subtitle">Verified device and inference information. Unknown means SnapMind could not prove the capability.</p></div>{error && <div className="alert error"><WifiOff size={17} /> {error}</div>}<div className="hardware-device panel"><div><p className="eyebrow">Device</p><h2>{hardware?.device.processor ?? 'Loading device information...'}</h2><span>{hardware?.device.os ?? 'Reading operating system evidence'}</span></div><Cpu className="heading-icon" size={25} /></div><div className="capability-grid">{capabilities.map((capability) => <div className="capability-card" key={capability.name}><div className="capability-top"><span>{capability.name}</span><span className={`state-badge ${capability.status}`}>{capability.status}</span></div><strong>{capability.status === 'available' ? 'Available' : capability.status === 'unknown' ? 'Unknown' : 'Unsupported'}</strong><p>{capability.evidence}</p>{capability.limitation && <small>{capability.limitation}</small>}</div>)}</div><div className="runtime-panel panel"><div className="panel-heading"><div><p className="eyebrow">Current inference path</p><h2>{runtime?.backend ?? 'Loading backend...'}</h2></div><Activity className="heading-icon" size={20} /></div><div className="runtime-details"><div><span>Model</span><strong>{runtime?.model ?? '--'}</strong></div><div><span>Runtime</span><strong>{runtime?.runtime ?? '--'}</strong></div><div><span>Status</span><strong>{runtime?.status ?? '--'}</strong></div></div><div className="evidence-note"><ShieldCheck size={16} /><span>{runtime?.evidence ?? 'Runtime evidence is being collected.'}</span></div>{runtime?.limitation && <div className="limitation-note">{runtime.limitation}</div>}</div><div className="multimodal-panel"><div className="panel-heading"><div><p className="eyebrow">Optional multimodal</p><h2>Capability readiness</h2></div><Sparkles className="heading-icon" size={20} /></div><div className="multimodal-list">{multimodalItems.map((item) => <div className="multimodal-row" key={item.name}><div><strong>{item.name}</strong><span>{item.evidence}</span></div><span className={`state-badge ${item.status}`}>{item.status}</span></div>)}</div><p className="limitation-note">Only capabilities with a verified local runtime and end-to-end test will be enabled.</p></div></section>
}

function BenchmarkPage() {
  const [result, setResult] = useState<import('./api').BenchmarkResult | null>(null)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const run = async () => { setBusy(true); setError(''); try { setResult(await api.benchmarkRetrieval('What does grounded generation require?')) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Benchmark failed.') } finally { setBusy(false) } }
  return <section className="benchmark-page"><div className="page-intro"><p className="eyebrow">System</p><h1>Benchmark</h1><p className="subtitle">Measure the verified local retrieval path used by the demo.</p></div><div className="benchmark-hero panel"><div><p className="eyebrow">RAG retrieval</p><h2>Measured on this machine</h2><p>Run a repeatable warm retrieval workload against the current local index.</p></div><button className="primary-button" onClick={run} disabled={busy}><Gauge size={17} />{busy ? 'Measuring...' : 'Run benchmark'}</button></div>{error && <div className="alert error"><WifiOff size={17} /> {error}</div>}{busy ? <div className="library-state"><Activity className="spin" size={23} /><strong>Measuring retrieval latency...</strong><span>Collecting local timings without changing indexed content.</span></div> : result ? <><div className="benchmark-metrics"><Metric label="Average latency" value={`${result.average_latency_ms} ms`} /><Metric label="Fastest run" value={`${result.minimum_latency_ms} ms`} /><Metric label="Slowest run" value={`${result.maximum_latency_ms} ms`} /><Metric label="Indexed chunks" value={String(result.indexed_chunks)} /></div><div className="benchmark-details panel"><div><span>Workload</span><strong>{result.workload}</strong></div><div><span>Iterations</span><strong>{result.iterations}</strong></div><div><span>Backend</span><strong>{result.backend}</strong></div><div><span>Runtime</span><strong>{result.runtime}</strong></div><div><span>Model</span><strong>{result.model}</strong></div></div><div className="evidence-note"><ShieldCheck size={16} /><span>Measured locally. This is a retrieval benchmark, not a claim of NPU/GPU or Snapdragon acceleration.</span></div></> : <div className="library-state"><Gauge size={25} /><strong>No benchmark run yet</strong><span>Run the measured workload after preparing the demo documents.</span></div>}</section>
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="metric-card"><span>{label}</span><strong>{value}</strong></div> }

function ChatPage() {
  const [messages, setMessages] = useState<import('./api').ChatMessage[]>([])
  const [query, setQuery] = useState('')
  const [busy, setBusy] = useState(false)
  const [stage, setStage] = useState('')
  const [error, setError] = useState('')
  const sessionId = useRef(`session-${crypto.randomUUID()}`)
  const send = async () => { if (!query.trim() || busy) return; const question = query.trim(); setQuery(''); setError(''); setBusy(true); setStage('Retrieving knowledge...'); try { await new Promise((resolve) => setTimeout(resolve, 200)); setStage('Preparing context...'); await new Promise((resolve) => setTimeout(resolve, 200)); setStage('Generating locally...'); const response = await api.chat(question, sessionId.current); setMessages(response.history); setStage('') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Chat request failed.'); setStage('') } finally { setBusy(false) } }
  return <section className="chat-page"><div className="chat-header"><div className="page-intro"><p className="eyebrow">Workspace</p><h1>Chat</h1><p className="subtitle">Ask questions grounded in your local knowledge base.</p></div><div className="model-badge"><span className="status-dot" /> Local model candidate</div></div><div className="chat-surface">{messages.length === 0 && !busy ? <div className="chat-empty"><div className="chat-empty-icon"><MessageSquare size={24} /></div><h2>Ask your knowledge anything.</h2><p>Answers are generated locally from retrieved document sources.</p><div className="suggestion-list"><button onClick={() => setQuery('What are the key concepts?')}>What are the key concepts?</button><button onClick={() => setQuery('Summarize the uploaded documents.')}>Summarize the uploaded documents.</button><button onClick={() => setQuery('Compare the available sources.')}>Compare the available sources.</button></div></div> : <div className="message-list">{messages.map((message, index) => <div className={`message ${message.role}`} key={`${message.role}-${index}`}><div className="message-label">{message.role === 'user' ? 'You' : 'SnapMind'}</div><div className="message-body">{message.content}</div>{message.citations.length > 0 && <div className="citation-list"><span className="citation-label">Sources</span>{message.citations.map((citation) => <div className="source-card" key={citation.chunk_id}><div><strong>[{citation.citation_id}] {citation.document_name}</strong><span>{citation.page ? `Page ${citation.page}` : 'Page unavailable'}{citation.section ? ` · ${citation.section}` : ''}</span></div><ArrowUpRight size={14} /></div>)}</div>}</div>)}{busy && <div className="message assistant"><div className="message-label">SnapMind</div><div className="generating"><span className="status-dot" />{stage}</div></div>}</div>} </div>{error && <div className="alert error"><WifiOff size={17} /> {error} <button className="retry-button" onClick={() => { setError(''); setQuery(query || 'Retry the last question') }}>Retry</button></div>}<div className="chat-composer"><textarea value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); send() } }} placeholder="Ask anything about your knowledge..." rows={1} /><button className="primary-button" onClick={send} disabled={busy || !query.trim()}><ArrowUpRight size={17} /> Send</button></div><div className="chat-footnote"><ShieldCheck size={14} /> Local retrieval and generation · No cloud AI calls</div></section>
}

function StudyPage() {
  const [tab, setTab] = useState<'summary' | 'key-points' | 'quiz' | 'flashcards'>('summary')
  const [detail, setDetail] = useState('short')
  const [response, setResponse] = useState<StudyResponse | null>(null)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const generate = async () => { setBusy(true); setError(''); try { setResponse(await api.study(tab, detail)) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Study generation failed.') } finally { setBusy(false) } }
  const data = response?.data ?? {}
  return <section className="study-page"><div className="page-intro"><p className="eyebrow">Workspace</p><h1>Study</h1><p className="subtitle">Create learning material from the documents in your local knowledge base.</p></div><div className="study-tabs">{([['summary', 'Summary', FileText], ['key-points', 'Key points', Sparkles], ['quiz', 'Quiz', Gauge], ['flashcards', 'Flashcards', BookOpen]] as const).map(([value, label, Icon]) => <button className={tab === value ? 'active' : ''} key={value} onClick={() => { setTab(value); setResponse(null); setError('') }}><Icon size={16} />{label}</button>)}</div><div className="study-controls"><select value={detail} onChange={(event) => setDetail(event.target.value)} aria-label="Summary detail"><option value="short">Short output</option><option value="detailed">Detailed output</option></select><button className="primary-button" onClick={generate} disabled={busy}><Sparkles size={16} />{busy ? 'Generating locally...' : 'Generate'}</button></div>{error && <div className="alert error"><WifiOff size={17} /> {error}<button className="retry-button" onClick={generate}>Retry</button></div>}{busy ? <div className="library-state"><Activity className="spin" size={23} /><strong>Preparing local study material...</strong><span>Retrieving sources and generating with the configured local model.</span></div> : response ? <StudyResult tab={tab} data={data} citations={response.citations} /> : <div className="library-state"><BookOpen size={25} /><strong>Choose a study action</strong><span>Every result is generated from indexed document content and includes source references.</span></div>}</section>
}
function StudyResult({ tab, data, citations }: { tab: string; data: Record<string, unknown>; citations: Citation[] }) { const source = (ids: unknown) => Array.isArray(ids) ? ids.map((id) => citations[Number(id) - 1]).filter(Boolean).map((citation) => <span key={citation.chunk_id} className="result-source">[{citation.citation_id}] {citation.document_name}{citation.page ? ` · Page ${citation.page}` : ''}</span>) : null; if (tab === 'summary') return <div className="study-result"><div className="study-section"><p className="eyebrow">Short summary</p><p className="study-copy">{String(data.short_summary ?? '')}</p></div><div className="study-section"><p className="eyebrow">Detailed summary</p><p className="study-copy">{String(data.detailed_summary ?? '')}</p></div>{Array.isArray(data.section_summaries) && <div className="study-list">{data.section_summaries.map((item, index) => { const section = item as Record<string, unknown>; return <article key={index}><h3>{String(section.title ?? 'Section')}</h3><p>{String(section.summary ?? '')}</p><div>{source(section.source_ids)}</div></article> })}</div>}</div>; if (tab === 'key-points') return <div className="study-list">{Array.isArray(data.key_points) && data.key_points.map((item, index) => { const point = item as Record<string, unknown>; return <article key={index}><span className="point-type">{String(point.type ?? 'takeaway')}</span><p>{String(point.text ?? '')}</p><div>{source(point.source_ids)}</div></article> })}</div>; if (tab === 'quiz') return <div className="study-list">{Array.isArray(data.questions) && data.questions.map((item, index) => { const question = item as Record<string, unknown>; return <article key={index}><h3>{index + 1}. {String(question.question ?? '')}</h3><ul>{Array.isArray(question.options) && question.options.map((option) => <li key={String(option)}>{String(option)}</li>)}</ul><p className="answer-line"><strong>Answer:</strong> {String(question.correct_answer ?? '')}</p><p>{String(question.explanation ?? '')}</p><div>{source(question.source_ids)}</div></article> })}</div>; return <div className="flashcard-grid">{Array.isArray(data.flashcards) && data.flashcards.map((item, index) => { const card = item as Record<string, unknown>; return <article key={index}><p className="eyebrow">Card {index + 1}</p><h3>{String(card.question ?? '')}</h3><p>{String(card.answer ?? '')}</p><div>{source(card.source_ids)}</div></article> })}</div> }

const pageInfo: Record<string, { kicker: string; title: string; description: string; icon: typeof FileText }> = {
  documents: { kicker: 'Workspace', title: 'Documents', description: 'Manage the local sources that will power your knowledge base.', icon: FileText },
  knowledge: { kicker: 'Workspace', title: 'Knowledge', description: 'Explore indexed sources and understand where answers come from.', icon: Boxes },
  chat: { kicker: 'Workspace', title: 'Chat', description: 'Ask questions about your imported knowledge.', icon: MessageSquare },
  study: { kicker: 'Workspace', title: 'Study', description: 'Turn your knowledge into summaries, quizzes, and flashcards.', icon: BookOpen },
  hardware: { kicker: 'System', title: 'Hardware', description: 'View verified device capabilities and runtime information.', icon: Cpu },
  benchmark: { kicker: 'System', title: 'Benchmark', description: 'Measure local AI performance when a model and runtime are configured.', icon: Gauge },
  settings: { kicker: 'System', title: 'Settings', description: 'Configure the workspace, models, privacy, and performance.', icon: Settings },
}
function PlaceholderPage({ page }: { page: keyof typeof pageInfo }) { const info = pageInfo[page]; const Icon = info.icon; const detail = page === 'benchmark' ? 'Measurements will appear after a verified workload is available.' : page === 'settings' ? 'Configuration controls will appear as local runtimes and preferences are added.' : 'This workspace is connected, but the feature is not configured yet.'; return <section className="placeholder-page"><div className="page-intro"><p className="eyebrow">{info.kicker}</p><h1>{info.title}</h1><p className="subtitle">{info.description}</p></div><div className="placeholder-panel"><div className="placeholder-icon"><Icon size={27} /></div><h2>Not configured yet.</h2><p>{detail}</p><div className="setup-line"><span className="status-dot" /> No verified data available</div></div></section> }

function App() { return <Routes><Route element={<AppShell />}><Route path="/" element={<Dashboard />} /><Route path="/documents" element={<DocumentsPage />} /><Route path="/knowledge" element={<KnowledgePage />} /><Route path="/chat" element={<ChatPage />} /><Route path="/study" element={<StudyPage />} /><Route path="/hardware" element={<HardwarePage />} /><Route path="/benchmark" element={<BenchmarkPage />} /><Route path="/settings" element={<PlaceholderPage page="settings" />} /></Route></Routes> }

createRoot(document.getElementById('root')!).render(<StrictMode><BrowserRouter><App /></BrowserRouter></StrictMode>)
